practice1/blog/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleDeleteView,
    ArticleUpdateView
)

app_name = 'articles'

urlpatterns = [
    path('', ArticleListView.as_view(), name='article_list'),
    # path('<int:pk>', ArticleDetailView.as_view(), name='article_detail'), # default usage
    path('<int:id>/', ArticleDetailView.as_view(), name='article_detail'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('<int:id>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
    path('<int:id>/update/', ArticleUpdateView.as_view(), name='article_update')
]

practice1/practice1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index_view, name='index'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('blog/', include('blog.urls'))
]

practice1/products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.products_home_view, name='products_index'),
    path('create/', views.products_create_view, name='products_create'),
    path('<int:id>/', views.products_get_by_id_view, name='product_get_by_id')
]

practice1/blog/models.py
from django.db import models

from django.urls import reverse

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.__class__.__name__}<{self.id}, {self.title}>"

    def __repr__(self):
        return self.__str__()

    def get_absolute_url(self):
        return reverse("articles:article_detail", kwargs={"id": self.id})

practice1/products/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Product(models.Model):
    title = models.CharField('Title', max_length=120)
    description = models.TextField('Description')
    price = models.DecimalField('Price', decimal_places=2, max_digits=1000)

    def __str__(self):
        return f"{self.__class__.__name__}<{self.id}, {self.title}>"

    def __repr__(self):
        return self.__str__()
    
    def get_absolute_url(self):
        return reverse("products:product_get_by_id", kwargs={"id": self.id})

practice1/blog/forms.py
from django import forms

from .models import Article


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={"placeholder": "Title"}))
    content = forms.CharField(label='Content', widget=forms.TextInput(attrs={"placeholder": "Your Content"}))
    class Meta:
        model = Article
        fields = [
            'title',
            'content'
        ]

practice1/products/forms.py
from django import forms

from .models import Product

class ProductForm(forms.ModelForm):
    # Override the default view
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={"placeholder": "Product Title"}))
    # description = forms.CharField(required=False, label='Description', widget=forms.TextInput(attrs={"placeholder": "Product Description"}))
    description = forms.CharField(label='Description', widget=forms.TextInput(attrs={"placeholder": "Product Description"}))
    price = forms.DecimalField(initial=0.0)
    class Meta:
        model = Product
        fields = [
            'title',
            'description',
            'price'
        ]

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if 'Product' in title:
            raise forms.ValidationError("Not a valid title")
        return title

practice1/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView
)

from .forms import ArticleForm
from .models import Article

# Create your views here.

class ArticleCreateView(CreateView):
    template_name = 'article/article_create.html'
    form_class = ArticleForm
    queryset = Article.objects.all()  # <blog>/<modelname>_list.html
    # success_url = '<path>'

    def form_valid(self, form):
        return super().form_valid(form)

    # def get_success_url(self):
    #     return <something>


class ArticleListView(ListView):
    template_name = 'article/article_list.html'
    queryset = Article.objects.all()  # <blog>/<modelname>_list.html


class ArticleDetailView(DetailView):
    template_name = 'article/article_detail.html'
    # queryset = Article.objects.all()  # <blog>/<modelname>_detail.html (default usage)

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Article, id=id_)
    

class ArticleUpdateView(UpdateView):
    template_name = 'article/article_create.html'
    form_class = ArticleForm

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Article, id=id_)

    def form_valid(self, form):
        return super().form_valid(form)


class ArticleDeleteView(DeleteView):
    template_name = 'article/article_delete.html'
    
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Article, id=id_)

    def get_success_url(self):
        return reverse('articles:article_list')

practice1/practice1/views.py
from django.shortcuts import render

# Create your views here.

def index_view(request):
    context = {
        "current_user": request.user
    }
    return render(request, 'base.html', context)

practice1/products/views.py
from django.shortcuts import render, get_object_or_404

from .models import Product

from .forms import ProductForm

# Create your views here.

def products_home_view(request):
    object_list = Product.objects.all()
    context = {
        'object_list': object_list
    }
    return render(request, 'products/index.html', context)


def products_create_view(request):
    form = ProductForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = ProductForm()
    context = {
        'form': form
    }
    return render(request, 'products/create.html', context)


def products_get_by_id_view(request, id):
    obj = get_object_or_404(Product, id=id)
    context = {
        'object': obj
    }
    return render(request, 'products/index.html', context)

practice1/blog/templates/article/article_create.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

practice1/blog/templates/article/article_delete.html
{% extends 'base.html' %}

{% block content %}


<form action='.' method='POST'>{% csrf_token %}
    <h1>Do you want to delete the post "{{ object.title }}"?</h1>
    <p><input type='submit' value='Yes' />  <a href='../'>Cancel</a></p>

</form>

{% endblock %}

practice1/blog/templates/article/article_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ object.title }}</h1>
<p>{{ object.content }}</p>
{% endblock %}

practice1/blog/templates/article/article_list.html
{% extends "base.html" %}

{% block content %}
<h1>Blog</h1>
{% if object_list %}
    <ol>
    {% for obj in object_list %}
        <li><p><a href={{ obj.get_absolute_url }}>{{obj.title}}</a><p>
            <button type="button"><a href="{% url 'articles:article_delete' obj.id %}">Delete</a></button>
            <button type="button"><a href="{% url 'articles:article_update' obj.id %}">Update</a></button>
        </li>

    {% endfor %}
    <ol>
{% else %}
    <p>Blog list is empty</p>
{% endif %}
{% endblock %}

practice1/products/templates/products/create.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value="Save"/>
</form>
{% endblock %}

practice1/products/templates/products/index.html
{% extends "base.html" %}

{% block content %}
<h1>Products</h1>
{% if object %}
    <ul>
        <li><p><a href={{ object.get_absolute_url }}>{{object.title}}</a><p></li>
    </ul>
{% elif object_list %}
    <ol>
    {% for obj in object_list %}
        <li><p><a href={{ obj.get_absolute_url }}>{{obj.title}}</a><p></li>
    {% endfor %}
    <ol>
{% else %}
    <p>Product list is empty</p>
{% endif %}
{% endblock %}

practice1/templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <title>Django Tutorial</title>
    </head>
    <body>
        {% include 'navigation.html' %}
        {% block content %}
        Welcome. Logged in as {{ current_user }}
        {% endblock %}
    </body>
</html>

practice1/templates/navigation.html
<nav>
    <ul>
        <li>Brand</li>
        <li>Contact</li>
        <li>About</li>
    </ul>
</nav>