corey_schafer/blog/urls.py
from django.urls import path, include

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='home-view'),
    path('user/<str:username>', views.UserPostListView.as_view(), name='user-posts-view'),
    path('post/create/', views.PostCreateView.as_view(), name='create-view'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail-view'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='update-view'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete-view'),
    path('about', views.about, name='about-view')
]

corey_schafer/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django_project import views

urlpatterns = [
    path('', views.index, name='home-view'),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

corey_schafer/users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views


app_name = 'users'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register')
]

corey_schafer/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

corey_schafer/users/models.py
from PIL import Image
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

corey_schafer/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from users.models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

corey_schafer/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import Post
# Create your views here.

posts = [
    {
        'author': 'CoreyMS',
        'title': 'Blog Post 1',
        'content': 'First post content',
        'date_posted': 'August 27, 2018'
    },
    {
        'author': 'Jane Doe',
        'title': 'Blog Post 2',
        'content': 'Second post content',
        'date_posted': 'August 28, 2018'
    }
]


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/index.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/index.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 1


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 1

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    success_url = reverse_lazy('blog:home-view')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']
    success_url = reverse_lazy('blog:home-view')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:home-view')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})

corey_schafer/django_project/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'base.html', {})

corey_schafer/users/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

corey_schafer/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}

Blog About Page

{% endblock %}

corey_schafer/blog/templates/blog/base.html
{% extends 'base.html' %}

{% block title %}
    {%if title %}
        Blog - {{ title }}
    {% else %}
        Blog
    {% endif %}
{% endblock %}

{% block base_content %}
    <main role="main" class="container" style="margin-top:100px">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

{% endblock %}

corey_schafer/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}

{% for post in posts %}
    <div class="card text-bg-light mb-3" style="width: 18rem;">
      <img class="card-img-top" src="{{ post.author.profile.image.url }}">
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'blog:detail-view' post.pk %}">{{ post.title }}</a></h5>
        <h6 class="card-subtitle mb-2 text-muted">Created By: <a href="{% url 'blog:user-posts-view' post.author.username %}">{{ post.author }}</a></h6>
        <small class="card-subtitle mb-2 text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        <p class="card-text">{{ post.content }}</p>
      </div>
    </div>
{% endfor %}

{% if is_paginated %}

  {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
      <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
  {% endif %}

{% endif %}

{% endblock %}

corey_schafer/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}Blog Post Delete{% endblock %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:detail-view' object.pk %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

corey_schafer/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}

<div class="card text-bg-light mb-3" style="width: 18rem;">
  <img class="card-img-top" src="{{ object.author.profile.image.url }}">
  <div class="card-body">
    <h5 class="card-title">{{ object.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">Created By: <a href="{% url 'blog:user-posts-view' object.author.username %}">{{ object.author }}</a></h6>
    <small class="card-subtitle mb-2 text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
    <p class="card-text">{{ object.content }}</p>
    {% if object.author == user %}
      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:update-view' object.id %}">Update</a>
      <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:delete-view' object.id %}">Delete</a>
    {% endif %}
  </div>
</div>

{% endblock %}

corey_schafer/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Blog Post{% endblock %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock %}

corey_schafer/blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}

{% block content %}

<h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>

{% for post in posts %}
    <div class="card text-bg-light mb-3" style="width: 18rem;">
      <img class="card-img-top" src="{{ post.author.profile.image.url }}">
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'blog:detail-view' post.pk %}">{{ post.title }}</a></h5>
        <h6 class="card-subtitle mb-2 text-muted">Created By: <a href="{% url 'blog:user-posts-view' post.author.username %}">{{ post.author }}</a></h6>
        <small class="card-subtitle mb-2 text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        <p class="card-text">{{ post.content }}</p>
      </div>
    </div>
{% endfor %}

{% if is_paginated %}

  {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
      <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
  {% endif %}

{% endif %}

{% endblock %}

corey_schafer/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    <header class="site-header">
        {% include 'navigation.html' %}
    </header>
    {% block base_content %}
        <div class="container bg-light" style="margin-top:100px">
            <h2>Welcome {{ request.user }}</h2>
        </div>
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
</body>
</html>

corey_schafer/templates/navigation.html
<!--<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">-->
<!--  <div class="container">-->
<!--    <a class="navbar-brand mr-4" href="{% url 'blog:home-view' %}">Blog</a>-->
<!--    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">-->
<!--    <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--    <div class="collapse navbar-collapse" id="navbarToggle">-->
<!--      <div class="navbar-nav mr-auto">-->
<!--        <a class="nav-item nav-link" href="{% url 'blog:home-view' %}">Home</a>-->
<!--        <a class="nav-item nav-link" href="{% url 'blog:about-view' %}">About</a>-->
<!--      </div>-->
<!--      &lt;!&ndash; Navbar Right Side &ndash;&gt;-->
<!--      <div class="navbar-nav">-->
<!--        <a class="nav-item nav-link" href="#">Login</a>-->
<!--        <a class="nav-item nav-link" href="#">Register</a>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</nav>-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'blog:home-view' %}">Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggle">
      <div class="navbar-nav me-auto mb-2 mb-lg-0">
        <a class="nav-link" aria-current="page" href="{% url 'blog:home-view' %}">Home</a>
        <a class="nav-link" aria-current="page" href="{% url 'blog:about-view' %}">About</a>
      </div>
      <div class="navbar-nav">
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'blog:create-view' %}">New Post</a>
          <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
          <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

corey_schafer/users/templates/users/base.html
{% extends 'base.html' %}

{% block title %}
    User
{% endblock %}

{% block base_content %}
    <main role="main" class="container mt-5" style="margin-top:100px">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

{% endblock %}

corey_schafer/users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block title %}User Login{% endblock %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'users:register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock %}

corey_schafer/users/templates/users/logout.html
{% extends "users/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'users:login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

corey_schafer/users/templates/users/profile.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
    </div>
{% endblock content %}

corey_schafer/users/templates/users/register.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block title %}User Registration{% endblock %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="#">Sign In</a>
            </small>
        </div>
    </div>
{% endblock %}